# Generated by Django 4.0.3 on 2024-12-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(default=0)),
                ('username', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('offer_link', models.CharField(max_length=250, null=True)),
                ('invited', models.IntegerField(default=0)),
                ('balance', models.BigIntegerField(default=0)),
            ],
        ),
    ]
