# Generated by Django 4.2.16 on 2024-10-13 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_course_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='telegram_id',
        ),
    ]
